### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by marksjc** [Gitoffthelawn/Contact-Gitoffthelawn#6]
Thanks for backing me up in the DDG export bookmarks discussion. I think I was as frustrated with DDG handling of issue as anyone, and even left the first dicey comment sit, but GitHub is not Twittter (else no usable code ever produced and we'd all think ourselves more whitty and profound than every other user but still be relieved ex-Seditionist banned).  I re-read the thread a couple more times today and then submitted a suggestion that moderators might play a more active role through user flagging.  I forgot to mention  NYT & Wash Post do that.  It's in GitHub if interested.  I'm not trying to drag you into anything, btw, just thought to thank you directly and tell you about my idea that might help (or not).  I always prefer a 3rd party intervention to de-personalize, rationalize and institutionalize rule enforcement (I'ze need an editor copywise). You wilingness to jump in to reinforce boundaries was very helpful and I felt glad I had addressed the issue & how.

**Comment by Gitoffthelawn** [comment]
@marksjc I sincerely appreciate your comments and feedback.  I think sites/apps like Twitter and Facebook have made it more of a challenge to find people willing to behave professionally, maturely, and respectfully online.  This is compounded by the lack of willingness of so many people to own up to their own dysfunctional behaviour.  This unwillingness to admit one's errors could possibly be at an all-time high; I've never seen anything like it before.  A simple *"I'm sorry, my bad."* goes such a long way.

I just clicked on the "follow" button on you profile so I'll have a quick link to your profile.  Feel free to write anytime.

**Comment by marksjc** [comment]
Thanks again.  It's often hard to distinguish "self awareness ignorance" from arrogant privilege. When guys (to be precise, generally white guys like me) react to mild criticism by claiming an abasing apology was demanded of them or that they are being personally attacked when their words were accusatory and dismissive and were specified as such it can be difficult to respond without feeding the faux righteous indignation. The dishonest behavior of elected officials promoting known lies is heartbreaking and devastating and they intentionally use the same indignation to assert their right to say whatever they want. Likewise, when the writer responded with the  arrogance of privilege and false presumption of honor, his agitated responses clarified the indictment.  I don't care about hurting his feelings but I don't want GitHub to allow bullying or priviledge BS to poison interaction.  I've written insensitive things elsewhere (but took responsponsibility & corrected them) and been bullied mercilessly once or twice.  So one learns both their own limits of communicating and what it's like to be harassed because you are disliked for no good reason.  I've found a common trait of claiming innocence based on literal words even when the context and intent were clearly accusatory or dismissive. Of course the powerful market dominators like Google never admit error or fault on their own forums and allow attacks or diminution of issues by fanboys and others then lock the discussion without comment. That corporate arrogance also magnifies bad behavior.

**Comment by marksjc** [comment]
I enjoyed the exchange of ideas and the shared understand of discourse and respect
